module header
	// Internal signals
	// Generated Signal List
	// End of Generated Signal List
	// %COMPILER_OPTS%
	// Generated Signal Assignments
	// Generated Instances and Port Mappings
	`ifdef insert_emu_mux_inst_ba
		// Emulator Data Injection Path, generated by MIX
		wire emu_mux_inst_ba = 1'b0;
	`endif
		// Generated Instance Port Map for inst_ba
		ent_ba inst_ba (
		);
		// End of Generated Instance Port Map for inst_ba
	`ifdef insert_emu_mux_inst_bb
		// Emulator Data Injection Path, generated by MIX
		wire emu_mux_inst_bb = 1'b0;
	`endif
		// Generated Instance Port Map for inst_bb
		ent_bb inst_bb (
		);
		// End of Generated Instance Port Map for inst_bb
endmodule