module  complex_mult_altera_mult_add_6f4g
	(
	aclr0,
	clock0,
	dataa,
	datab,
	ena0,
	ena1,
	ena2,
	ena3,
	result) ;
	input   aclr0;
	input   clock0;
	input   [63:0]  dataa;
	input   [19:0]  datab;
	input   ena0;
	input   ena1;
	input   ena2;
	input   ena3;
	output   [41:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr0;
	tri1   clock0;
	tri0   [63:0]  dataa;
	tri0   [19:0]  datab;
	tri1   ena0;
	tri1   ena1;
	tri1   ena2;
	tri1   ena3;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif
	wire  [41:0]   wire_altera_mult_add_rtl2_result;
	altera_mult_add_rtl   altera_mult_add_rtl2
	(
	.aclr0(aclr0),
	.chainout_sat_overflow(),
	.clock0(clock0),
	.dataa(dataa),
	.datab(datab),
	.ena0(ena0),
	.ena1(ena1),
	.ena2(ena2),
	.ena3(ena3),
	.mult0_is_saturated(),
	.mult1_is_saturated(),
	.mult2_is_saturated(),
	.mult3_is_saturated(),
	.overflow(),
	.result(wire_altera_mult_add_rtl2_result),
	.scanouta(),
	.scanoutb(),
	.accum_sload(1'b0),
	.aclr1(1'b0),
	.aclr2(1'b0),
	.aclr3(1'b0),
	.addnsub1(1'b1),
	.addnsub1_round(1'b0),
	.addnsub3(1'b1),
	.addnsub3_round(1'b0),
	.chainin({1{1'b0}}),
	.chainout_round(1'b0),
	.chainout_saturate(1'b0),
	.clock1(1'b1),
	.clock2(1'b1),
	.clock3(1'b1),
	.coefsel0({3{1'b0}}),
	.coefsel1({3{1'b0}}),
	.coefsel2({3{1'b0}}),
	.coefsel3({3{1'b0}}),
	.datac({44{1'b0}}),
	.mult01_round(1'b0),
	.mult01_saturation(1'b0),
	.mult23_round(1'b0),
	.mult23_saturation(1'b0),
	.output_round(1'b0),
	.output_saturate(1'b0),
	.rotate(1'b0),
	.scanina({32{1'b0}}),
	.scaninb({10{1'b0}}),
	.shift_right(1'b0),
	.signa(1'b0),
	.signb(1'b0),
	.sload_accum(1'b0),
	.sourcea({2{1'b0}}),
	.sourceb({2{1'b0}}),
	.zero_chainout(1'b0),
	.zero_loopback(1'b0)
	);
	defparam
		altera_mult_add_rtl2.accum_direction = "ADD",
		altera_mult_add_rtl2.accum_sload_aclr = "ACLR0",
		altera_mult_add_rtl2.accum_sload_latency_aclr = "NONE",
		altera_mult_add_rtl2.accum_sload_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.accum_sload_register = "CLOCK0",
		altera_mult_add_rtl2.accumulator = "NO",
		altera_mult_add_rtl2.adder1_rounding = "NO",
		altera_mult_add_rtl2.adder3_rounding = "NO",
		altera_mult_add_rtl2.addnsub1_round_aclr = "ACLR0",
		altera_mult_add_rtl2.addnsub1_round_pipeline_aclr = "ACLR0",
		altera_mult_add_rtl2.addnsub1_round_pipeline_register = "CLOCK0",
		altera_mult_add_rtl2.addnsub1_round_register = "CLOCK0",
		altera_mult_add_rtl2.addnsub3_round_aclr = "ACLR0",
		altera_mult_add_rtl2.addnsub3_round_pipeline_aclr = "ACLR0",
		altera_mult_add_rtl2.addnsub3_round_pipeline_register = "CLOCK0",
		altera_mult_add_rtl2.addnsub3_round_register = "CLOCK0",
		altera_mult_add_rtl2.addnsub_multiplier_aclr1 = "ACLR0",
		altera_mult_add_rtl2.addnsub_multiplier_aclr3 = "ACLR0",
		altera_mult_add_rtl2.addnsub_multiplier_latency_aclr1 = "NONE",
		altera_mult_add_rtl2.addnsub_multiplier_latency_aclr3 = "NONE",
		altera_mult_add_rtl2.addnsub_multiplier_latency_clock1 = "UNREGISTERED",
		altera_mult_add_rtl2.addnsub_multiplier_latency_clock3 = "UNREGISTERED",
		altera_mult_add_rtl2.addnsub_multiplier_register1 = "CLOCK0",
		altera_mult_add_rtl2.addnsub_multiplier_register3 = "CLOCK0",
		altera_mult_add_rtl2.chainout_aclr = "ACLR0",
		altera_mult_add_rtl2.chainout_adder = "NO",
		altera_mult_add_rtl2.chainout_register = "CLOCK0",
		altera_mult_add_rtl2.chainout_round_aclr = "ACLR0",
		altera_mult_add_rtl2.chainout_round_output_aclr = "ACLR0",
		altera_mult_add_rtl2.chainout_round_output_register = "CLOCK0",
		altera_mult_add_rtl2.chainout_round_pipeline_aclr = "ACLR0",
		altera_mult_add_rtl2.chainout_round_pipeline_register = "CLOCK0",
		altera_mult_add_rtl2.chainout_round_register = "CLOCK0",
		altera_mult_add_rtl2.chainout_rounding = "NO",
		altera_mult_add_rtl2.chainout_saturate_aclr = "ACLR0",
		altera_mult_add_rtl2.chainout_saturate_output_aclr = "ACLR0",
		altera_mult_add_rtl2.chainout_saturate_output_register = "CLOCK0",
		altera_mult_add_rtl2.chainout_saturate_pipeline_aclr = "ACLR0",
		altera_mult_add_rtl2.chainout_saturate_pipeline_register = "CLOCK0",
		altera_mult_add_rtl2.chainout_saturate_register = "CLOCK0",
		altera_mult_add_rtl2.chainout_saturation = "NO",
		altera_mult_add_rtl2.coef0_0 = 0,
		altera_mult_add_rtl2.coef0_1 = 0,
		altera_mult_add_rtl2.coef0_2 = 0,
		altera_mult_add_rtl2.coef0_3 = 0,
		altera_mult_add_rtl2.coef0_4 = 0,
		altera_mult_add_rtl2.coef0_5 = 0,
		altera_mult_add_rtl2.coef0_6 = 0,
		altera_mult_add_rtl2.coef0_7 = 0,
		altera_mult_add_rtl2.coef1_0 = 0,
		altera_mult_add_rtl2.coef1_1 = 0,
		altera_mult_add_rtl2.coef1_2 = 0,
		altera_mult_add_rtl2.coef1_3 = 0,
		altera_mult_add_rtl2.coef1_4 = 0,
		altera_mult_add_rtl2.coef1_5 = 0,
		altera_mult_add_rtl2.coef1_6 = 0,
		altera_mult_add_rtl2.coef1_7 = 0,
		altera_mult_add_rtl2.coef2_0 = 0,
		altera_mult_add_rtl2.coef2_1 = 0,
		altera_mult_add_rtl2.coef2_2 = 0,
		altera_mult_add_rtl2.coef2_3 = 0,
		altera_mult_add_rtl2.coef2_4 = 0,
		altera_mult_add_rtl2.coef2_5 = 0,
		altera_mult_add_rtl2.coef2_6 = 0,
		altera_mult_add_rtl2.coef2_7 = 0,
		altera_mult_add_rtl2.coef3_0 = 0,
		altera_mult_add_rtl2.coef3_1 = 0,
		altera_mult_add_rtl2.coef3_2 = 0,
		altera_mult_add_rtl2.coef3_3 = 0,
		altera_mult_add_rtl2.coef3_4 = 0,
		altera_mult_add_rtl2.coef3_5 = 0,
		altera_mult_add_rtl2.coef3_6 = 0,
		altera_mult_add_rtl2.coef3_7 = 0,
		altera_mult_add_rtl2.coefsel0_aclr = "ACLR0",
		altera_mult_add_rtl2.coefsel0_latency_aclr = "NONE",
		altera_mult_add_rtl2.coefsel0_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.coefsel0_register = "CLOCK0",
		altera_mult_add_rtl2.coefsel1_aclr = "ACLR0",
		altera_mult_add_rtl2.coefsel1_latency_aclr = "NONE",
		altera_mult_add_rtl2.coefsel1_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.coefsel1_register = "CLOCK0",
		altera_mult_add_rtl2.coefsel2_aclr = "ACLR0",
		altera_mult_add_rtl2.coefsel2_latency_aclr = "NONE",
		altera_mult_add_rtl2.coefsel2_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.coefsel2_register = "CLOCK0",
		altera_mult_add_rtl2.coefsel3_aclr = "ACLR0",
		altera_mult_add_rtl2.coefsel3_latency_aclr = "NONE",
		altera_mult_add_rtl2.coefsel3_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.coefsel3_register = "CLOCK0",
		altera_mult_add_rtl2.dedicated_multiplier_circuitry = "AUTO",
		altera_mult_add_rtl2.double_accum = "NO",
		altera_mult_add_rtl2.dsp_block_balancing = "Auto",
		altera_mult_add_rtl2.extra_latency = 0,
		altera_mult_add_rtl2.input_a0_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_a0_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_a1_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_a1_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_a2_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_a2_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_a3_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_a3_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_aclr_a0 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_a1 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_a2 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_a3 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_b0 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_b1 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_b2 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_b3 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_c0 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_c1 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_c2 = "ACLR0",
		altera_mult_add_rtl2.input_aclr_c3 = "ACLR0",
		altera_mult_add_rtl2.input_b0_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_b0_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_b1_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_b1_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_b2_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_b2_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_b3_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_b3_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_c0_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_c0_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_c1_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_c1_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_c2_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_c2_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_c3_latency_aclr = "NONE",
		altera_mult_add_rtl2.input_c3_latency_clock = "UNREGISTERED",
		altera_mult_add_rtl2.input_register_a0 = "CLOCK0",
		altera_mult_add_rtl2.input_register_a1 = "CLOCK0",
		altera_mult_add_rtl2.input_register_a2 = "CLOCK0",
		altera_mult_add_rtl2.input_register_a3 = "CLOCK0",
		altera_mult_add_rtl2.input_register_b0 = "CLOCK0",
		altera_mult_add_rtl2.input_register_b1 = "CLOCK0",
		altera_mult_add_rtl2.input_register_b2 = "CLOCK0",
		altera_mult_add_rtl2.input_register_b3 = "CLOCK0",
		altera_mult_add_rtl2.input_register_c0 = "CLOCK0",
		altera_mult_add_rtl2.input_register_c1 = "CLOCK0",
		altera_mult_add_rtl2.input_register_c2 = "CLOCK0",
		altera_mult_add_rtl2.input_register_c3 = "CLOCK0",
		altera_mult_add_rtl2.input_source_a0 = "DATAA",
		altera_mult_add_rtl2.input_source_a1 = "DATAA",
		altera_mult_add_rtl2.input_source_a2 = "DATAA",
		altera_mult_add_rtl2.input_source_a3 = "DATAA",
		altera_mult_add_rtl2.input_source_b0 = "DATAB",
		altera_mult_add_rtl2.input_source_b1 = "DATAB",
		altera_mult_add_rtl2.input_source_b2 = "DATAB",
		altera_mult_add_rtl2.input_source_b3 = "DATAB",
		altera_mult_add_rtl2.latency = 0,
		altera_mult_add_rtl2.loadconst_control_aclr = "ACLR0",
		altera_mult_add_rtl2.loadconst_control_register = "CLOCK0",
		altera_mult_add_rtl2.loadconst_value = 64,
		altera_mult_add_rtl2.mult01_round_aclr = "ACLR0",
		altera_mult_add_rtl2.mult01_round_register = "CLOCK0",
		altera_mult_add_rtl2.mult01_saturation_aclr = "ACLR1",
		altera_mult_add_rtl2.mult01_saturation_register = "CLOCK0",
		altera_mult_add_rtl2.mult23_round_aclr = "ACLR0",
		altera_mult_add_rtl2.mult23_round_register = "CLOCK0",
		altera_mult_add_rtl2.mult23_saturation_aclr = "ACLR0",
		altera_mult_add_rtl2.mult23_saturation_register = "CLOCK0",
		altera_mult_add_rtl2.multiplier01_rounding = "NO",
		altera_mult_add_rtl2.multiplier01_saturation = "NO",
		altera_mult_add_rtl2.multiplier1_direction = "SUB",
		altera_mult_add_rtl2.multiplier23_rounding = "NO",
		altera_mult_add_rtl2.multiplier23_saturation = "NO",
		altera_mult_add_rtl2.multiplier3_direction = "ADD",
		altera_mult_add_rtl2.multiplier_aclr0 = "ACLR0",
		altera_mult_add_rtl2.multiplier_aclr1 = "ACLR0",
		altera_mult_add_rtl2.multiplier_aclr2 = "ACLR0",
		altera_mult_add_rtl2.multiplier_aclr3 = "ACLR0",
		altera_mult_add_rtl2.multiplier_register0 = "CLOCK0",
		altera_mult_add_rtl2.multiplier_register1 = "CLOCK0",
		altera_mult_add_rtl2.multiplier_register2 = "CLOCK0",
		altera_mult_add_rtl2.multiplier_register3 = "CLOCK0",
		altera_mult_add_rtl2.number_of_multipliers = 2,
		altera_mult_add_rtl2.output_aclr = "ACLR0",
		altera_mult_add_rtl2.output_register = "CLOCK0",
		altera_mult_add_rtl2.output_round_aclr = "ACLR0",
		altera_mult_add_rtl2.output_round_pipeline_aclr = "ACLR0",
		altera_mult_add_rtl2.output_round_pipeline_register = "CLOCK0",
		altera_mult_add_rtl2.output_round_register = "CLOCK0",
		altera_mult_add_rtl2.output_round_type = "NEAREST_INTEGER",
		altera_mult_add_rtl2.output_rounding = "NO",
		altera_mult_add_rtl2.output_saturate_aclr = "ACLR0",
		altera_mult_add_rtl2.output_saturate_pipeline_aclr = "ACLR0",
		altera_mult_add_rtl2.output_saturate_pipeline_register = "CLOCK0",
		altera_mult_add_rtl2.output_saturate_register = "CLOCK0",
		altera_mult_add_rtl2.output_saturate_type = "ASYMMETRIC",
		altera_mult_add_rtl2.output_saturation = "NO",
		altera_mult_add_rtl2.port_addnsub1 = "PORT_UNUSED",
		altera_mult_add_rtl2.port_addnsub3 = "PORT_UNUSED",
		altera_mult_add_rtl2.port_chainout_sat_is_overflow = "PORT_UNUSED",
		altera_mult_add_rtl2.port_output_is_overflow = "PORT_UNUSED",
		altera_mult_add_rtl2.port_signa = "PORT_UNUSED",
		altera_mult_add_rtl2.port_signb = "PORT_UNUSED",
		altera_mult_add_rtl2.preadder_direction_0 = "ADD",
		altera_mult_add_rtl2.preadder_direction_1 = "ADD",
		altera_mult_add_rtl2.preadder_direction_2 = "ADD",
		altera_mult_add_rtl2.preadder_direction_3 = "ADD",
		altera_mult_add_rtl2.preadder_mode = "SIMPLE",
		altera_mult_add_rtl2.representation_a = "SIGNED",
		altera_mult_add_rtl2.representation_b = "SIGNED",
		altera_mult_add_rtl2.rotate_aclr = "ACLR0",
		altera_mult_add_rtl2.rotate_output_aclr = "ACLR0",
		altera_mult_add_rtl2.rotate_output_register = "CLOCK0",
		altera_mult_add_rtl2.rotate_pipeline_aclr = "ACLR0",
		altera_mult_add_rtl2.rotate_pipeline_register = "CLOCK0",
		altera_mult_add_rtl2.rotate_register = "CLOCK0",
		altera_mult_add_rtl2.scanouta_aclr = "ACLR0",
		altera_mult_add_rtl2.scanouta_register = "UNREGISTERED",
		altera_mult_add_rtl2.selected_device_family = "Cyclone V",
		altera_mult_add_rtl2.shift_mode = "NO",
		altera_mult_add_rtl2.shift_right_aclr = "ACLR0",
		altera_mult_add_rtl2.shift_right_output_aclr = "ACLR0",
		altera_mult_add_rtl2.shift_right_output_register = "CLOCK0",
		altera_mult_add_rtl2.shift_right_pipeline_aclr = "ACLR0",
		altera_mult_add_rtl2.shift_right_pipeline_register = "CLOCK0",
		altera_mult_add_rtl2.shift_right_register = "CLOCK0",
		altera_mult_add_rtl2.signed_aclr_a = "ACLR0",
		altera_mult_add_rtl2.signed_aclr_b = "ACLR0",
		altera_mult_add_rtl2.signed_latency_aclr_a = "NONE",
		altera_mult_add_rtl2.signed_latency_aclr_b = "NONE",
		altera_mult_add_rtl2.signed_latency_clock_a = "UNREGISTERED",
		altera_mult_add_rtl2.signed_latency_clock_b = "UNREGISTERED",
		altera_mult_add_rtl2.signed_register_a = "CLOCK0",
		altera_mult_add_rtl2.signed_register_b = "CLOCK0",
		altera_mult_add_rtl2.systolic_aclr1 = "ACLR0",
		altera_mult_add_rtl2.systolic_aclr3 = "ACLR0",
		altera_mult_add_rtl2.systolic_delay1 = "UNREGISTERED",
		altera_mult_add_rtl2.systolic_delay3 = "UNREGISTERED",
		altera_mult_add_rtl2.use_sload_accum_port = "NO",
		altera_mult_add_rtl2.width_a = 32,
		altera_mult_add_rtl2.width_b = 10,
		altera_mult_add_rtl2.width_c = 22,
		altera_mult_add_rtl2.width_chainin = 1,
		altera_mult_add_rtl2.width_coef = 18,
		altera_mult_add_rtl2.width_msb = 17,
		altera_mult_add_rtl2.width_result = 42,
		altera_mult_add_rtl2.width_saturate_sign = 1,
		altera_mult_add_rtl2.zero_chainout_output_aclr = "ACLR0",
		altera_mult_add_rtl2.zero_chainout_output_register = "CLOCK0",
		altera_mult_add_rtl2.zero_loopback_aclr = "ACLR0",
		altera_mult_add_rtl2.zero_loopback_output_aclr = "ACLR0",
		altera_mult_add_rtl2.zero_loopback_output_register = "CLOCK0",
		altera_mult_add_rtl2.zero_loopback_pipeline_aclr = "ACLR0",
		altera_mult_add_rtl2.zero_loopback_pipeline_register = "CLOCK0",
		altera_mult_add_rtl2.zero_loopback_register = "CLOCK0",
		altera_mult_add_rtl2.lpm_type = "altera_mult_add_rtl";
	assign
		result = wire_altera_mult_add_rtl2_result;
endmodule